apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evolvia-backend-cleanup-trigger-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    environment: production
    app: evolvia-backend
    component: backend-cleanup-trigger
    type: cronjob
spec:
  project: cloudmentor
  destination:
    server: https://kubernetes.default.svc
    namespace: evolvia-backend-cronjobs-prod

  sources:
    - repoURL: ghcr.io/cloudsteak/charts
      chart: evolvia-backend-cleanup-trigger
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/apps/production/evolvia-backend/components/evolvia-backend-cleanup-trigger/values.yaml
    - repoURL: https://github.com/cloudsteak/cm-companion
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
