apiVersion: v1
kind: Namespace
metadata:
  name: evolvia-backend-prod
  labels:
    cloudsteak.io/ghcr-auth: "true"
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cron-jobs
  labels:
    cloudsteak.io/ghcr-auth: "true"
    istio-injection: enabled
