apiVersion: v1
kind: Namespace
metadata:
  name: evolvia-backend-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    cloudsteak.io/ghcr-auth: "true"
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: evolvia-backend-cronjobs-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    cloudsteak.io/ghcr-auth: "true"
    istio-injection: enabled
