apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-automation-app
  namespace: n8n-prod
  labels:
    environment: production
    app: n8n-automation
    component: n8n
    managed-by: argocd
spec:
  replicas: 0
  selector:
    matchLabels:
      app: n8n-automation
      component: n8n
  template:
    metadata:
      labels:
        app: n8n-automation
        component: n8n
    spec:
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:2.20.9
          ports:
            - containerPort: 5678
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: n8n-postgres-rw.n8n-prod.svc.cluster.local
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n-prod
            - name: DB_POSTGRESDB_USER
              value: automation-master
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-prod-secrets
                  key: DB_POSTGRESDB_PASSWORD
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-prod-secrets
                  key: N8N_ENCRYPTION_KEY
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
              value: "false"
            - name: N8N_GIT_NODE_DISABLE_BARE_REPOS
              value: "true"
            - name: WEBHOOK_URL
              value: "https://n8n.tools.cloud-mentor.hu"
            - name: N8N_EDITOR_BASE_URL
              value: "https://n8n.tools.cloud-mentor.hu"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-automation-app
  namespace: n8n-prod
  labels:
    environment: production
    app: n8n-automation
    component: n8n
    managed-by: argocd
spec:
  selector:
    app: n8n-automation
    component: n8n
  ports:
    - port: 80
      targetPort: 5678
