apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-prod-secrets
  namespace: n8n-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: n8n-prod-secrets
  data:
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: /prod/app/n8n/config
        property: POSTGRES.DB_PASSWORD
    - secretKey: DB_POSTGRESDB_USER
      remoteRef:
        key: /prod/app/n8n/config
        property: POSTGRES.DB_USER
    - secretKey: DB_POSTGRESDB_DATABASE
      remoteRef:
        key: /prod/app/n8n/config
        property: POSTGRES.DB_NAME
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: /prod/app/n8n/config
        property: N8N.ENCRYPTION_KEY
