apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-automation-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    environment: production
    app: n8n-automation
    component: n8n
    type: application
spec:
  project: cloudmentor
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-prod
  sources:
    - repoURL: oci://8gears.container-registry.com/library/n8n
      chart: n8n
      targetRevision: "2.0.1"
      helm:
        valueFiles:
          - $values/apps/production/n8n-automation/components/n8n/values.yaml
    - repoURL: https://github.com/cloudsteak/cm-companion
      targetRevision: main
      ref: values
    - repoURL: https://github.com/cloudsteak/cm-companion
      targetRevision: main
      path: apps/production/n8n-automation/components/n8n/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
