apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: evolvia-backend-cleanup-trigger-credentials
  namespace: evolvia-backend-cronjobs-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: evolvia-backend-cleanup-trigger-credentials
  data:
    - secretKey: INTERNAL_SECRET
      remoteRef:
        key: /prod/app/evolvia-backend-cleanup-trigger/credentials
        property: security.internal_secret
    - secretKey: BACKEND_URL
      remoteRef:
        key: /prod/app/evolvia-backend-cleanup-trigger/credentials
        property: api.backend_url
