apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: evolvia-backend-cleanup-trigger-credentials
  namespace: cron-jobs
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: evolvia-backend-cleanup-trigger-credentials
  data:
    - secretKey: INTERNAL_SECRET
      remoteRef:
        key: /prod/app/evolvia-backend-cleanup-trigger/credentials
        property: security.internal_secret
    - secretKey: BACKEND_URL
      remoteRef:
        key: /prod/app/evolvia-backend-cleanup-trigger/credentials
        property: api.backend_url
